"""empty message

Revision ID: 243e6833365e
Revises: 749d8dd9eeb3
Create Date: 2025-10-06 21:28:08.685487

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '243e6833365e'
down_revision = '749d8dd9eeb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_priority', 'queues', ['priority'], unique=False)
    op.add_column('robots', sa.Column('type', sa.String(length=20), nullable=True, comment='类型：faq-常见问题，keyword-智能关键词'))
    op.drop_column('service_groups', 'created_at')
    op.add_column('system_settings', sa.Column('robot_reply_mode', sa.String(length=20), nullable=True, comment='机器人回复模式：always-始终回复，offline_only-仅离线时回复'))
    op.alter_column('system_settings', 'upload_allowed_types',
               existing_type=mysql.TEXT(),
               comment='客服允许的文件类型（逗号分隔）',
               existing_comment='允许的文件类型（逗号分隔）',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_settings', 'upload_allowed_types',
               existing_type=mysql.TEXT(),
               comment='允许的文件类型（逗号分隔）',
               existing_comment='客服允许的文件类型（逗号分隔）',
               existing_nullable=True)
    op.drop_column('system_settings', 'robot_reply_mode')
    op.add_column('service_groups', sa.Column('created_at', mysql.DATETIME(), nullable=True, comment='创建时间'))
    op.drop_column('robots', 'type')
    op.drop_index('idx_priority', table_name='queues')
    # ### end Alembic commands ###
