"""empty message

Revision ID: 48e5187efe58
Revises: 243e6833365e
Create Date: 2025-10-08 20:44:32.709130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48e5187efe58'
down_revision = '243e6833365e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'chats', 'services', ['service_id'], ['service_id'])
    op.add_column('queues', sa.Column('last_message_time', sa.DateTime(), nullable=True, comment='最后消息时间'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queues', 'last_message_time')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    # ### end Alembic commands ###
