"""add_ip_location_fields

Revision ID: 749d8dd9eeb3
Revises: a6db0e84b40c
Create Date: 2025-10-06 09:56:45.187710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '749d8dd9eeb3'
down_revision = 'a6db0e84b40c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitors', sa.Column('country', sa.String(length=100), nullable=True, comment='国家'))
    op.add_column('visitors', sa.Column('province', sa.String(length=100), nullable=True, comment='省份/州'))
    op.add_column('visitors', sa.Column('city', sa.String(length=100), nullable=True, comment='城市'))
    op.add_column('visitors', sa.Column('country_code', sa.String(length=10), nullable=True, comment='国家代码'))
    op.add_column('visitors', sa.Column('latitude', sa.Float(), nullable=True, comment='纬度'))
    op.add_column('visitors', sa.Column('longitude', sa.Float(), nullable=True, comment='经度'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visitors', 'longitude')
    op.drop_column('visitors', 'latitude')
    op.drop_column('visitors', 'country_code')
    op.drop_column('visitors', 'city')
    op.drop_column('visitors', 'province')
    op.drop_column('visitors', 'country')
    # ### end Alembic commands ###
