"""empty message

Revision ID: 9e0bf968d4c2
Revises: ba08d449a122
Create Date: 2025-10-05 15:19:06.097389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e0bf968d4c2'
down_revision = 'ba08d449a122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitors', sa.Column('user_agent', sa.String(length=512), nullable=True, comment='User-Agent'))
    op.add_column('visitors', sa.Column('browser', sa.String(length=128), nullable=True, comment='浏览器'))
    op.add_column('visitors', sa.Column('os', sa.String(length=128), nullable=True, comment='操作系统'))
    op.add_column('visitors', sa.Column('device', sa.String(length=128), nullable=True, comment='设备类型'))
    op.add_column('visitors', sa.Column('referrer', sa.String(length=512), nullable=True, comment='来源页面'))
    op.add_column('visitors', sa.Column('utm_source', sa.String(length=128), nullable=True, comment='UTM来源'))
    op.add_column('visitors', sa.Column('utm_medium', sa.String(length=128), nullable=True, comment='UTM媒介'))
    op.add_column('visitors', sa.Column('utm_campaign', sa.String(length=128), nullable=True, comment='UTM活动'))
    op.add_column('visitors', sa.Column('group_id', sa.Integer(), nullable=True, comment='分组ID'))
    op.add_column('visitors', sa.Column('tags', sa.String(length=512), nullable=True, comment='标签，逗号分隔'))
    op.add_column('visitors', sa.Column('is_blacklist', sa.SmallInteger(), nullable=True, comment='是否黑名单'))
    op.add_column('visitors', sa.Column('first_visit_time', sa.DateTime(), nullable=True, comment='首次访问时间'))
    op.add_column('visitors', sa.Column('last_visit_time', sa.DateTime(), nullable=True, comment='最后访问时间'))
    op.create_index('idx_group_id', 'visitors', ['group_id'], unique=False)
    op.create_index('idx_state', 'visitors', ['state'], unique=False)
    op.create_foreign_key(None, 'visitors', 'visitor_groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visitors', type_='foreignkey')
    op.drop_index('idx_state', table_name='visitors')
    op.drop_index('idx_group_id', table_name='visitors')
    op.drop_column('visitors', 'last_visit_time')
    op.drop_column('visitors', 'first_visit_time')
    op.drop_column('visitors', 'is_blacklist')
    op.drop_column('visitors', 'tags')
    op.drop_column('visitors', 'group_id')
    op.drop_column('visitors', 'utm_campaign')
    op.drop_column('visitors', 'utm_medium')
    op.drop_column('visitors', 'utm_source')
    op.drop_column('visitors', 'referrer')
    op.drop_column('visitors', 'device')
    op.drop_column('visitors', 'os')
    op.drop_column('visitors', 'browser')
    op.drop_column('visitors', 'user_agent')
    # ### end Alembic commands ###
