"""add_system_settings

Revision ID: a6db0e84b40c
Revises: 9e0bf968d4c2
Create Date: 2025-10-06 09:39:23.062865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6db0e84b40c'
down_revision = '9e0bf968d4c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False, comment='商户ID'),
    sa.Column('upload_max_size', sa.Integer(), nullable=True, comment='最大文件大小（字节，默认10MB）'),
    sa.Column('upload_allowed_types', sa.Text(), nullable=True, comment='允许的文件类型（逗号分隔）'),
    sa.Column('upload_image_max_size', sa.Integer(), nullable=True, comment='最大图片大小（字节，默认5MB）'),
    sa.Column('chat_welcome_text', sa.Text(), nullable=True, comment='欢迎语'),
    sa.Column('chat_offline_text', sa.Text(), nullable=True, comment='离线提示'),
    sa.Column('chat_queue_text', sa.Text(), nullable=True, comment='排队提示'),
    sa.Column('session_timeout', sa.Integer(), nullable=True, comment='会话超时时间（秒，默认30分钟）'),
    sa.Column('auto_close_timeout', sa.Integer(), nullable=True, comment='自动关闭超时（秒，默认5分钟）'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_settings')
    # ### end Alembic commands ###
