"""empty message

Revision ID: ba08d449a122
Revises: 
Create Date: 2025-10-05 13:50:27.157995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba08d449a122'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=100), nullable=False, comment='商户名称'),
    sa.Column('logo', sa.String(length=255), nullable=True, comment='Logo'),
    sa.Column('copyright', sa.String(length=255), nullable=True, comment='版权信息'),
    sa.Column('video_state', sa.Enum('open', 'close'), nullable=True, comment='视频状态'),
    sa.Column('audio_state', sa.Enum('open', 'close'), nullable=True, comment='音频状态'),
    sa.Column('voice_state', sa.Enum('open', 'close'), nullable=True, comment='语音提示'),
    sa.Column('template_state', sa.Enum('open', 'close'), nullable=True, comment='模板消息'),
    sa.Column('distribution_rule', sa.Enum('auto', 'claim'), nullable=True, comment='分配规则'),
    sa.Column('voice_address', sa.String(length=255), nullable=True, comment='提示音地址'),
    sa.Column('push_url', sa.String(length=255), nullable=True, comment='推送URL'),
    sa.Column('state', sa.Enum('open', 'close'), nullable=True, comment='商户状态'),
    sa.Column('is_delete', sa.SmallInteger(), nullable=True, comment='是否删除'),
    sa.Column('lang', sa.String(length=50), nullable=True, comment='语言'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False, comment='商户ID'),
    sa.Column('title', sa.String(length=128), nullable=False, comment='评价说明'),
    sa.Column('comments', sa.Text(), nullable=False, comment='评价条目（JSON）'),
    sa.Column('word_switch', sa.Enum('open', 'close'), nullable=True, comment='文字评价开关'),
    sa.Column('word_title', sa.String(length=32), nullable=False, comment='文字评价标题'),
    sa.Column('add_time', sa.DateTime(), nullable=True, comment='添加时间'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('qid', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False, comment='商户ID'),
    sa.Column('question', sa.Text(), nullable=False, comment='问题'),
    sa.Column('keyword', sa.String(length=12), nullable=True, comment='关键词'),
    sa.Column('answer', sa.Text(), nullable=False, comment='答案（HTML）'),
    sa.Column('answer_text', sa.Text(), nullable=False, comment='答案（纯文本）'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='状态：1显示 0不显示'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('qid')
    )
    op.create_index('idx_business_id', 'questions', ['business_id'], unique=False)
    op.create_index('idx_keyword', 'questions', ['keyword'], unique=False)
    op.create_table('robots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False, comment='商户ID'),
    sa.Column('keyword', sa.String(length=12), nullable=False, comment='关键词'),
    sa.Column('reply', sa.Text(), nullable=False, comment='回复内容'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='状态：1显示 0不显示'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_business_id', 'robots', ['business_id'], unique=False)
    op.create_index('idx_keyword', 'robots', ['keyword'], unique=False)
    op.create_table('service_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groupname', sa.String(length=255), nullable=True, comment='分组名称'),
    sa.Column('business_id', sa.Integer(), nullable=False, comment='商户ID'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False, comment='用户名'),
    sa.Column('nick_name', sa.String(length=255), nullable=False, comment='昵称'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('business_id', sa.Integer(), nullable=False, comment='商户ID'),
    sa.Column('group_id', sa.String(length=225), nullable=True, comment='客服分组'),
    sa.Column('phone', sa.String(length=255), nullable=True, comment='手机号'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='邮箱'),
    sa.Column('avatar', sa.String(length=1024), nullable=True, comment='头像'),
    sa.Column('level', sa.Enum('super_manager', 'manager', 'service'), nullable=True, comment='权限级别'),
    sa.Column('state', sa.Enum('online', 'offline'), nullable=True, comment='在线状态'),
    sa.Column('offline_first', sa.SmallInteger(), nullable=True, comment='优先离线'),
    sa.Column('open_id', sa.String(length=255), nullable=True, comment='微信OpenID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('service_id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('visitors',
    sa.Column('vid', sa.Integer(), nullable=False),
    sa.Column('visitor_id', sa.String(length=200), nullable=False, comment='访客唯一ID'),
    sa.Column('visitor_name', sa.String(length=255), nullable=False, comment='访客名称'),
    sa.Column('channel', sa.String(length=255), nullable=False, comment='访客频道'),
    sa.Column('avatar', sa.String(length=1024), nullable=False, comment='头像'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='真实姓名'),
    sa.Column('tel', sa.String(length=32), nullable=True, comment='电话'),
    sa.Column('connect', sa.Text(), nullable=True, comment='联系方式'),
    sa.Column('comment', sa.Text(), nullable=True, comment='备注'),
    sa.Column('business_id', sa.Integer(), nullable=False, comment='商户ID'),
    sa.Column('ip', sa.String(length=255), nullable=False, comment='IP地址'),
    sa.Column('from_url', sa.String(length=255), nullable=False, comment='来源URL'),
    sa.Column('login_times', sa.Integer(), nullable=True, comment='登录次数'),
    sa.Column('extends', sa.Text(), nullable=True, comment='浏览器扩展信息'),
    sa.Column('state', sa.Enum('online', 'offline'), nullable=True, comment='在线状态'),
    sa.Column('is_top', sa.SmallInteger(), nullable=True, comment='是否置顶'),
    sa.Column('msg_time', sa.DateTime(), nullable=True, comment='最后消息时间'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('vid'),
    sa.UniqueConstraint('visitor_id', 'business_id', name='uix_visitor_business')
    )
    op.create_index('idx_business_id', 'visitors', ['business_id'], unique=False)
    op.create_index('idx_visitor_id', 'visitors', ['visitor_id'], unique=False)
    op.create_table('chats',
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('visitor_id', sa.String(length=200), nullable=False, comment='访客ID'),
    sa.Column('service_id', sa.Integer(), nullable=False, comment='客服ID'),
    sa.Column('business_id', sa.Integer(), nullable=False, comment='商户ID'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('msg_type', sa.SmallInteger(), nullable=True, comment='消息类型'),
    sa.Column('direction', sa.Enum('to_visitor', 'to_service'), nullable=True, comment='消息方向'),
    sa.Column('state', sa.Enum('read', 'unread'), nullable=True, comment='阅读状态'),
    sa.Column('unstr', sa.String(length=32), nullable=True, comment='唯一字符串'),
    sa.Column('timestamp', sa.Integer(), nullable=False, comment='时间戳'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.service_id'], ),
    sa.PrimaryKeyConstraint('cid')
    )
    op.create_index('idx_business_id', 'chats', ['business_id'], unique=False)
    op.create_index('idx_service_id', 'chats', ['service_id'], unique=False)
    op.create_index('idx_timestamp', 'chats', ['timestamp'], unique=False)
    op.create_index('idx_visitor_id', 'chats', ['visitor_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False, comment='商户ID'),
    sa.Column('service_id', sa.Integer(), nullable=False, comment='客服ID'),
    sa.Column('group_id', sa.Integer(), nullable=True, comment='分组ID'),
    sa.Column('visitor_id', sa.String(length=200), nullable=False, comment='访客ID'),
    sa.Column('visitor_name', sa.String(length=255), nullable=False, comment='访客名称'),
    sa.Column('word_comment', sa.Text(), nullable=False, comment='文字评价'),
    sa.Column('add_time', sa.DateTime(), nullable=True, comment='添加时间'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.service_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_business_id', 'comments', ['business_id'], unique=False)
    op.create_index('idx_service_id', 'comments', ['service_id'], unique=False)
    op.create_table('queues',
    sa.Column('qid', sa.Integer(), nullable=False),
    sa.Column('visitor_id', sa.String(length=200), nullable=False, comment='访客ID'),
    sa.Column('service_id', sa.Integer(), nullable=False, comment='客服ID'),
    sa.Column('business_id', sa.Integer(), nullable=False, comment='商户ID'),
    sa.Column('group_id', sa.Integer(), nullable=True, comment='客服分组ID'),
    sa.Column('state', sa.Enum('normal', 'complete', 'blacklist'), nullable=True, comment='会话状态'),
    sa.Column('remind_tpl', sa.SmallInteger(), nullable=True, comment='是否已发送模板消息'),
    sa.Column('remind_comment', sa.SmallInteger(), nullable=True, comment='是否已推送评价'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.service_id'], ),
    sa.PrimaryKeyConstraint('qid')
    )
    op.create_index('idx_business_id', 'queues', ['business_id'], unique=False)
    op.create_index('idx_service_id', 'queues', ['service_id'], unique=False)
    op.create_index('idx_state', 'queues', ['state'], unique=False)
    op.create_index('idx_visitor_id', 'queues', ['visitor_id'], unique=False)
    op.create_table('visitor_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False, comment='商户ID'),
    sa.Column('service_id', sa.Integer(), nullable=False, comment='客服ID'),
    sa.Column('group_name', sa.String(length=128), nullable=False, comment='分组名称'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='状态'),
    sa.Column('bgcolor', sa.String(length=7), nullable=True, comment='背景色'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.service_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False, comment='评价ID'),
    sa.Column('title', sa.String(length=32), nullable=False, comment='评价项标题'),
    sa.Column('score', sa.SmallInteger(), nullable=True, comment='评分'),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_details')
    op.drop_table('visitor_groups')
    op.drop_index('idx_visitor_id', table_name='queues')
    op.drop_index('idx_state', table_name='queues')
    op.drop_index('idx_service_id', table_name='queues')
    op.drop_index('idx_business_id', table_name='queues')
    op.drop_table('queues')
    op.drop_index('idx_service_id', table_name='comments')
    op.drop_index('idx_business_id', table_name='comments')
    op.drop_table('comments')
    op.drop_index('idx_visitor_id', table_name='chats')
    op.drop_index('idx_timestamp', table_name='chats')
    op.drop_index('idx_service_id', table_name='chats')
    op.drop_index('idx_business_id', table_name='chats')
    op.drop_table('chats')
    op.drop_index('idx_visitor_id', table_name='visitors')
    op.drop_index('idx_business_id', table_name='visitors')
    op.drop_table('visitors')
    op.drop_table('services')
    op.drop_table('service_groups')
    op.drop_index('idx_keyword', table_name='robots')
    op.drop_index('idx_business_id', table_name='robots')
    op.drop_table('robots')
    op.drop_index('idx_keyword', table_name='questions')
    op.drop_index('idx_business_id', table_name='questions')
    op.drop_table('questions')
    op.drop_table('comment_settings')
    op.drop_table('businesses')
    # ### end Alembic commands ###
